### ISSUE TITLE
CSS Grid

### ISSUE THREAD

**Issue by loua0013** [loua0013/components-on-a-grid#1]
Hey @mackenzierose !!

I'm wondering why the second and third images are not respecting my grid system!

Thank you so much!

**Comment by loua0013** [comment]
This is a hot mess LOL

**Comment by loua0013** [comment]
I THINK IM GETTING IT! Thank you! Althought i might re-open this issue LOL

**Comment by loua0013** [comment]
Ok back at it! @mackenzieRose do you know why my logo isn't going to the bottom of the banner? Thank you!

**Comment by loua0013** [comment]
I tried making the banner fit into two columns and three rows so i can place the nav at the top right and the logo at the bottom left but I know we are supposed to use the grid-areas... i know we can use grid-template-columns with grid-areas but can we also use grid-template-rows WITH grid-areas? Thank you!!!

**Comment by MacKenzieRose** [comment]
I would suggest adding `align-self: end` to your current `.logo` CSS, and that should do what you want 🙂

**Comment by loua0013** [comment]
Amazing! Thank you for your help @Mackenzierose!!! You're the best!
